[package]
name = "blackhole"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.56.0"
gl = "0.14.0"
image = "0.25" 
nalgebra-glm = "0.18.0"
chrono = "0.4"

[build-dependencies]
gl_generator = "0.14.0"
